project:
  type: website
  output-dir: _site

website:
  title: "Md Kamrul Hasan"
  site-url: "https://mdkamrulhasan.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/mdkamrulhasan
        aria-label: GitHub profile

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
